// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocerApi.Context;

#nullable disable

namespace SocerApi.Migrations
{
    [DbContext(typeof(SocerPlayerInfoDbContext))]
    partial class SocerPlayerInfoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocerApi.Models.PostPlayerInfo", b =>
                {
                    b.Property<int>("playerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("playerId"));

                    b.Property<string>("clubName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberOfPlayingMatchInWorldCup")
                        .HasColumnType("int");

                    b.Property<int>("numberOfplayeingWorldCup")
                        .HasColumnType("int");

                    b.Property<string>("playerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("playingPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("playerId");

                    b.ToTable("postPlayerInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
